# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time

name: Build

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload App JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/app.jar