name: Deploy to EC2

on:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read

    steps:
      - name: Checkout (needed to access artifacts metadata if needed)
        uses: actions/checkout@v4

      - name: Download Artifact (Fat JAR)
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./deploy
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_ssh_key
          chmod 600 ~/.ssh/ec2_ssh_key
          
          cat <<EOF > ~/.ssh/config
          Host my-ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USER }}
            IdentityFile ~/.ssh/ec2_ssh_key
            StrictHostKeyChecking no
          EOF

      - name: Push JAR to EC2 via rsync
        run: |
          rsync -avz ./deploy/app.jar my-ec2:/home/${{ secrets.EC2_USER }}/app.jar

      - name: Deploy JAR on EC2
        run: |
          ssh my-ec2 << 'EOF'
            echo "✅ Checking Java version..."
            java -version || { echo "Java is not installed!"; exit 1; }
          
            echo "🛑 Killing existing app.jar processes..."
            pkill -f app.jar || echo "No running app.jar found"
          
            echo "🚀 Starting app.jar..."
            nohup java -jar /home/${USER}/app.jar > app.log 2>&1 &
          
            sleep 5  # wait a few seconds to allow the process to start
          
            echo "🔍 Verifying app.jar is running..."
            pgrep -f "java -jar /home/.*/app.jar" > /dev/null
          
            if [ $? -eq 0 ]; then
              echo "✅ app.jar is running."
            else
              echo "❌ app.jar failed to start."
              exit 1
            fi
          EOF